### ISSUE TITLE
genode / gart on Nexus 7?

### ISSUE THREAD

**Issue by dckc** [Componolit/gart#84]
I'm interested to run genode on an old Nexus 7 tablet. I read your FOSDEM slides with interest and I wonder if you think it's feasible with a moderate amount of effort.

 - [A Component-based Environment for Android Apps][1]  
  Alexander Senier  
  FOSDEM, Brussels, 2020-02-02

[1]: https://fosdem.org/2020/schedule/event/uk_android/attachments/slides/4087/export/events/attachments/uk_android/slides/4087/2020_02_02_GART.pdf

**Comment by senier** [comment]
Frankly, I'm not sure there is a way to accomplish that with moderate effort. The challenge is long before you can even think of executing the Android runtime. You need platform support for that particular device and drivers for the required devices. There are two general options: Port Genode to the device (e.g. using base-hw) or use base-linux with the existing Linux kernel available for the Nexus 7.

As ARM SoCs are so diverse, the first option definitely is somewhere between non-trivial and infeasible (e.g. due to lack of documentation for the SoC). I'm not aware of any support for the Nvidia Tegra 3 SoC. And given that the device is discontinued and the chipset is rather dated, doing such a port may simply not be worth the time.

The second option - base-linux - may be a little more promising. There are [folks out there](https://lists.genode.org/pipermail/users/2019-October/006948.html) using base-linux on ARMv7 (but maybe not on a tablet). You'll probably still need some (stub) drivers to interface with the framebuffer and touch input at least.

**Comment by dckc** [comment]
Thanks for sharing what you know promptly.
